module.exports = [
  // atom
  { method: 'post', path: 'atom/preferredRoles', controller: 'atom' },
  { method: 'post', path: 'atom/preferredRole', controller: 'atom' },
  { method: 'post', path: 'atom/preferredRoleId', controller: 'atom' },
  {
    method: 'post',
    path: 'atom/default',
    controller: 'atom',
    meta: { right: { type: 'atom', action: 'create' } },
  },
  {
    method: 'post',
    path: 'atom/create',
    controller: 'atom',
    middlewares: 'transaction',
    meta: { right: { type: 'atom', action: 'create' } },
  },
  { method: 'post', path: 'atom/atomClass', controller: 'atom', meta: { right: { type: 'atom', action: 'read' } } },
  { method: 'post', path: 'atom/read', controller: 'atom', meta: { right: { type: 'atom', action: 'read' } } },
  { method: 'post', path: 'atom/select', controller: 'atom', meta: { right: { type: 'atom', action: 'select' } } },
  { method: 'post', path: 'atom/count', controller: 'atom', meta: { right: { type: 'atom', action: 'select' } } },
  {
    method: 'post',
    path: 'atom/write',
    controller: 'atom',
    middlewares: 'transaction',
    meta: { right: { type: 'atom', action: 'write', stage: 'draft' } },
  },
  {
    method: 'post',
    path: 'atom/openDraft',
    controller: 'atom',
    middlewares: 'transaction',
    meta: { right: { type: 'atom', action: 'write' } },
  },
  {
    method: 'post',
    path: 'atom/submit',
    controller: 'atom',
    middlewares: 'transaction',
    meta: { right: { type: 'atom', action: 'write', stage: 'draft' } },
  },
  {
    method: 'post',
    path: 'atom/delete',
    controller: 'atom',
    middlewares: 'transaction',
    meta: { right: { type: 'atom', action: 'delete' } },
  },
  {
    method: 'post',
    path: 'atom/clone',
    controller: 'atom',
    middlewares: 'transaction',
    meta: { right: { type: 'atom', action: 'clone' } },
  },
  {
    method: 'post',
    path: 'atom/enable',
    controller: 'atom',
    middlewares: 'transaction',
    meta: { right: { type: 'atom', action: 'enable' } },
  },
  {
    method: 'post',
    path: 'atom/disable',
    controller: 'atom',
    middlewares: 'transaction',
    meta: { right: { type: 'atom', action: 'disable' } },
  },
  {
    method: 'post',
    path: 'atom/deleteBulk',
    controller: 'atom',
    middlewares: 'transaction',
    meta: { right: { type: 'atom', action: 'deleteBulk' } },
  },
  {
    method: 'post',
    path: 'atom/exportBulk',
    controller: 'atom',
    meta: { right: { type: 'atom', action: 'exportBulk' } },
  },
  {
    method: 'post',
    path: 'atom/importBulk',
    controller: 'atom',
    meta: { right: { type: 'atom', action: 'importBulk' } },
  },
  {
    method: 'post',
    path: 'atom/performAction',
    controller: 'atom',
    meta: { right: { type: 'atom', action: 'performAction' } },
  },
  {
    method: 'post',
    path: 'atom/performActionBulk',
    controller: 'atom',
    meta: { right: { type: 'atom', action: 'performActionBulk' } },
  },
  {
    method: 'post',
    path: 'atom/star',
    controller: 'atom',
    meta: {
      auth: { user: true },
      right: { type: 'atom', action: 'read' },
    },
  },
  {
    method: 'post',
    path: 'atom/readCount',
    controller: 'atom',
    meta: { right: { type: 'atom', action: 'read', checkFlow: true } },
  },
  { method: 'post', path: 'atom/stats', controller: 'atom' },
  {
    method: 'post',
    path: 'atom/labels',
    controller: 'atom',
    meta: {
      auth: { user: true },
      right: { type: 'atom', action: 'read' },
    },
  },
  { method: 'post', path: 'atom/actions', controller: 'atom' },
  { method: 'post', path: 'atom/actionsBulk', controller: 'atom' },
  { method: 'post', path: 'atom/schema', controller: 'atom' },
  { method: 'post', path: 'atom/validator', controller: 'atom' },
  { method: 'post', path: 'atom/checkRightAction', controller: 'atom' },
  {
    method: 'post',
    path: 'atom/moveUp',
    controller: 'atom',
    meta: { right: { type: 'atom', action: 'moveUp' } },
  },
  {
    method: 'post',
    path: 'atom/moveDown',
    controller: 'atom',
    meta: { right: { type: 'atom', action: 'moveDown' } },
  },
];
