/** beans: begin */
export * from '../bean/aop.category.js';
export * from '../bean/bean.atom.js';
export * from '../bean/bean.atomAction.js';
export * from '../bean/bean.atomBase.js';
export * from '../bean/bean.atomClass.js';
export * from '../bean/bean.atomRightAux.js';
export * from '../bean/bean.atomStage.js';
export * from '../bean/bean.atomState.js';
export * from '../bean/bean.atomStatic.js';
export * from '../bean/bean.auth.js';
export * from '../bean/bean.base.js';
export * from '../bean/bean.bodyCrypto.js';
export * from '../bean/bean.category.js';
export * from '../bean/bean.formAction.js';
export * from '../bean/bean.resource.js';
export * from '../bean/bean.role.js';
export * from '../bean/bean.stash.js';
export * from '../bean/bean.tag.js';
export * from '../bean/bean.user.js';
export * from '../bean/bean.util.js';
export * from '../bean/middleware.auth.js';
export * from '../bean/middleware.authOpen.js';
export * from '../bean/middleware.cors.js';
export * from '../bean/middleware.gate.js';
export * from '../bean/middleware.httpLog.js';
export * from '../bean/middleware.inner.js';
export * from '../bean/middleware.io.connectionAuth.js';
export * from '../bean/middleware.jsonp.js';
export * from '../bean/middleware.right.js';
export * from '../bean/middleware.test.js';
export * from '../bean/middleware.transaction.js';
export * from '../bean/queue.roleBuild.js';
export * from '../bean/queue.schedule.js';
export * from '../bean/startup.checkResourceLocales.js';
export * from '../bean/startup.checkViewHistoryRight.js';
export * from '../bean/startup.loadAtomStatics.js';
export * from '../bean/startup.loadSchedules.js';
export * from '../bean/startup.outputHomeRoute.js';
export * from '../bean/stats.draftsCommon.js';
export * from '../bean/stats.draftsFlowing.js';
export * from '../bean/stats.labels.js';
export * from '../bean/stats.stars.js';
export * from '../bean/stats.starsLabels.js';
export * from '../bean/summer.cache.atomClassInner.js';
export * from '../bean/summer.cache.roleParentsOfUser.js';
export * from '../bean/summer.cache.roleScopesMineOfUser.js';
export * from '../bean/summer.cache.roleScopesOfRole.js';
export * from '../bean/summer.cache.roleScopesOfUser.js';
export * from '../bean/summer.cache.roleWhosOfAtomClassAction.js';
export * from '../bean/version.manager.js';
import { BeanAtom } from '../bean/bean.atom.js';
import { BeanAtomAction } from '../bean/bean.atomAction.js';
import { BeanAtomBase } from '../bean/bean.atomBase.js';
import { BeanAtomClass } from '../bean/bean.atomClass.js';
import { BeanAtomRightAux } from '../bean/bean.atomRightAux.js';
import { BeanAtomStage } from '../bean/bean.atomStage.js';
import { BeanAtomState } from '../bean/bean.atomState.js';
import { BeanAtomStatic } from '../bean/bean.atomStatic.js';
import { BeanAuth } from '../bean/bean.auth.js';
import { BeanBase } from '../bean/bean.base.js';
import { BeanBodyCrypto } from '../bean/bean.bodyCrypto.js';
import { BeanCategory } from '../bean/bean.category.js';
import { BeanFormAction } from '../bean/bean.formAction.js';
import { BeanResource } from '../bean/bean.resource.js';
import { BeanRole } from '../bean/bean.role.js';
import { BeanStash } from '../bean/bean.stash.js';
import { BeanTag } from '../bean/bean.tag.js';
import { BeanUser } from '../bean/bean.user.js';
import { BeanUtil } from '../bean/bean.util.js';
import 'vona';
declare module 'vona' {
  export interface IBeanRecord {
    atom: BeanAtom;
    atomAction: BeanAtomAction;
    atomBase: BeanAtomBase;
    atomClass: BeanAtomClass;
    atomRightAux: BeanAtomRightAux;
    atomStage: BeanAtomStage;
    atomState: BeanAtomState;
    atomStatic: BeanAtomStatic;
    auth: BeanAuth;
    base: BeanBase;
    bodyCrypto: BeanBodyCrypto;
    category: BeanCategory;
    formAction: BeanFormAction;
    resource: BeanResource;
    role: BeanRole;
    stash: BeanStash;
    tag: BeanTag;
    user: BeanUser;
    util: BeanUtil;
  }
}
/** beans: end */
/** atoms: begin */
export * from '../atom/resource.js';
export * from '../atom/role.js';
export * from '../atom/roleFieldsRight.js';
export * from '../atom/roleFieldsRightSpread.js';
export * from '../atom/roleResourceRight.js';
export * from '../atom/roleResourceRightSpread.js';
export * from '../atom/roleRight.js';
export * from '../atom/roleRightSpread.js';
export * from '../atom/user.js';
export * from '../atom/userAtomRight.js';
export * from '../atom/userFieldsRight.js';
export * from '../atom/userResourceRight.js';
/** atoms: end */
