packages:
  - 'packages-cabloy/*'
  - 'packages-egg-born/*'
  - 'packages-utils/*'
  - 'src/module/*'
  - 'src/module-system/*'
  - 'src/module-vendor/*'
  - 'src/suite/*/modules/*'
  - 'src/suite-vendor/*/modules/*'
