packages:
  - 'packages-cli/*'
  - 'packages-utils/*'
  - 'packages-vona/*'
  - 'src/module/*'
  - 'src/module-vendor/*'
  - 'src/suite/*'
  - 'src/suite/*/modules/*'
  - 'src/suite-vendor/*'
  - 'src/suite-vendor/*/modules/*'
hoist: true
hoist-workspace-packages: true
public-hoist-pattern:
  - '*babel*'
  - '*@babel*'
  - '*eslint*'
  - '*types*'
  - 'lerna'
  - 'vona'
  - '*vona*'
  - 'cabloy'
  - '@cabloy'
  - '*cabloy*'
  - '*@cabloy*'
  - '*why-is-node-running*'
  - '*ts-node*'
  - 'zod'
link-workspace-packages: 'deep'
prefer-workspace-packages: true
auto-install-peers: true