packages:
  - 'packages-cli/*'
  - 'packages-docs'
  - 'packages-utils/*'
  - 'packages-vona/*'
  - 'src/module/*'
  - 'src/module-vendor/*'
  - 'src/suite/*'
  - 'src/suite/*/modules/*'
  - 'src/suite-vendor/*'
  - 'src/suite-vendor/*/modules/*'
