import { IModuleRoute } from 'vona';
import base from './route/base.js';
import atom from './route/atom.js';
import atomClass from './route/atomClass.js';
import atomState from './route/atomState.js';
import comment from './route/comment.js';
import user from './route/user.js';
import resource from './route/resource.js';
import auth from './route/auth.js';
import jwt from './route/jwt.js';
import util from './route/util.js';
import layoutConfig from './route/layoutConfig.js';
import category from './route/category.js';
import tag from './route/tag.js';

let routes: IModuleRoute[] = [];
routes = routes.concat(base);
routes = routes.concat(atom);
routes = routes.concat(atomClass);
routes = routes.concat(atomState);
routes = routes.concat(comment);
routes = routes.concat(user);
routes = routes.concat(resource);
routes = routes.concat(auth);
routes = routes.concat(jwt);
routes = routes.concat(util);
routes = routes.concat(layoutConfig);
routes = routes.concat(category);
routes = routes.concat(tag);

export { routes };
