export * from '../model/atom.js';
export * from '../model/atomAction.js';
export * from '../model/atomClass.js';
export * from '../model/auth.js';
export * from '../model/authProvider.js';
export * from '../model/role.js';
export * from '../model/roleInc.js';
export * from '../model/roleIncRef.js';
export * from '../model/roleRef.js';
export * from '../model/roleRight.js';
export * from '../model/roleRightRef.js';
export * from '../model/roleExpand.js';
export * from '../model/roleFieldsRight.js';
export * from '../model/user.js';
export * from '../model/userAgent.js';
export * from '../model/userRole.js';
export * from '../model/userRoleIncRef.js';
export * from '../model/userRoleRef.js';
export * from '../model/label.js';
export * from '../model/atomLabel.js';
export * from '../model/atomLabelRef.js';
export * from '../model/atomStar.js';
export * from '../model/comment.js';
export * from '../model/commentView.js';
export * from '../model/commentHeart.js';
export * from '../model/category.js';
export * from '../model/tag.js';
export * from '../model/tagRef.js';
export * from '../model/resource.js';
export * from '../model/resourceLocale.js';
export * from '../model/resourceRole.js';

import { ModelAtom } from '../model/atom.js';
import { ModelAtomAction } from '../model/atomAction.js';
import { ModelAtomClass } from '../model/atomClass.js';
import { ModelAuth } from '../model/auth.js';
import { ModelAuthProvider } from '../model/authProvider.js';
import { ModelRole } from '../model/role.js';
import { ModelRoleInc } from '../model/roleInc.js';
import { ModelRoleIncRef } from '../model/roleIncRef.js';
import { ModelRoleRef } from '../model/roleRef.js';
import { ModelRoleRight } from '../model/roleRight.js';
import { ModelRoleRightRef } from '../model/roleRightRef.js';
import { ModelRoleExpand } from '../model/roleExpand.js';
import { ModelRoleFieldsRight } from '../model/roleFieldsRight.js';
import { ModelUser } from '../model/user.js';
import { ModelUserAgent } from '../model/userAgent.js';
import { ModelUserRole } from '../model/userRole.js';
import { ModelUserRoleIncRef } from '../model/userRoleIncRef.js';
import { ModelUserRoleRef } from '../model/userRoleRef.js';
import { ModelLabel } from '../model/label.js';
import { ModelAtomLabel } from '../model/atomLabel.js';
import { ModelAtomLabelRef } from '../model/atomLabelRef.js';
import { ModelAtomStar } from '../model/atomStar.js';
import { ModelComment } from '../model/comment.js';
import { ModelCommentView } from '../model/commentView.js';
import { ModelCommentHeart } from '../model/commentHeart.js';
import { ModelCategory } from '../model/category.js';
import { ModelTag } from '../model/tag.js';
import { ModelTagRef } from '../model/tagRef.js';
import { ModelResource } from '../model/resource.js';
import { ModelResourceLocale } from '../model/resourceLocale.js';
import { ModelResourceRole } from '../model/resourceRole.js';

export interface IModuleModel {
  atom: ModelAtom;
  atomAction: ModelAtomAction;
  atomClass: ModelAtomClass;
  auth: ModelAuth;
  authProvider: ModelAuthProvider;
  role: ModelRole;
  roleInc: ModelRoleInc;
  roleIncRef: ModelRoleIncRef;
  roleRef: ModelRoleRef;
  roleRight: ModelRoleRight;
  roleRightRef: ModelRoleRightRef;
  roleExpand: ModelRoleExpand;
  roleFieldsRight: ModelRoleFieldsRight;
  user: ModelUser;
  userAgent: ModelUserAgent;
  userRole: ModelUserRole;
  userRoleIncRef: ModelUserRoleIncRef;
  userRoleRef: ModelUserRoleRef;
  label: ModelLabel;
  atomLabel: ModelAtomLabel;
  atomLabelRef: ModelAtomLabelRef;
  atomStar: ModelAtomStar;
  comment: ModelComment;
  commentView: ModelCommentView;
  commentHeart: ModelCommentHeart;
  category: ModelCategory;
  tag: ModelTag;
  tagRef: ModelTagRef;
  resource: ModelResource;
  resourceLocale: ModelResourceLocale;
  resourceRole: ModelResourceRole;
}
