export enum Errors {
  'Task not Found: %s' = 1001,
  'Task cannot be accessed: %s' = 1002,
  'Task has been claimed: %s' = 1003,
  'Task should be claimed first: %s' = 1004,
  'Task has been handled: %s' = 1005,
  'Task cannot be passed: %s' = 1006,
  'Task cannot be rejected: %s' = 1007,
  'Task Assignees cannot be empty: %s' = 1008,
  'Task Assignees cannot be appended: %s' = 1009,
  'Flow cannot be cancelled: %s' = 1010,
  'Task Handle Remark cannot be appended: %s' = 1011,
  'Task has been forwarded: %s' = 1012,
  'Task has been substituted: %s' = 1013,
}
