name: project-test
on:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [24]
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      pg:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ''
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4
        with:
          version: 10    
      - run: npm i tsx -g 
      - run: npm i vona-cli -g
      - run: vona :create:project vona-test --template=basic
      - run: vona :create:module demo-student --suite --description --author --ci
        working-directory: vona-test
      - run: pnpm install --no-frozen-lockfile
        working-directory: vona-test
      - run: vona :tools:crud student --module=demo-student
        working-directory: vona-test  
      - run: npm run test
        working-directory: vona-test
      - run: npm run build -- --flavor=ci
        working-directory: vona-test
      - run: SERVER_LISTEN_DISABLE=true npm run demo -- --mode=prod --flavor=ci
        working-directory: vona-test
